#This will download the current dev version of the 'drupal-composer/drupal-project' project into a folder named 'my_site_name_dir' 
# and then automatically executes composer install which will download the latest stable version of Drupal 8 
# and all its dependencies.

composer create-project drupal-composer/drupal-project:8.x-dev my_site_name_dir --no-interaction

####################################################################
#
# Some really helpful modules that you can use in almost all cases.
#
####################################################################

# Redirect
composer require 'drupal/redirect:^1.4'

# Pathauto (The Pathauto module automatically generates URL/path aliases for various kinds of content)
composer require 'drupal/pathauto:^1.4'

# CookieConsent (CookieConsent is a module that provides a solution to deal with the EU Cookie Law.)
composer require 'drupal/cookieconsent:^1.4'

# Metatag (The Metatag module allows you to automatically provide structured metadata)
# https://www.drupal.org/project/metatag
composer require 'drupal/metatag:^1.10'
 
# Adminimal - Responsive Administration Theme
composer require 'drupal/adminimal_theme:^1.5'

# Adminimal Admin Toolbar
composer require 'drupal/adminimal_admin_toolbar:^1.9'

# Linkit
# Linkit provides an easy interface for internal and external linking with wysiwyg editors by using an autocomplete field.
composer require 'drupal/linkit:^4.3'

####################################################################
#
# Other awesome Drupal 8 modules you should / could use
#
####################################################################

# D8 Editor File upload : This module allows to add a button in the Drupal 8 rich text editor active toolbar to directly upload and link files into your content. 
# https://www.drupal.org/project/editor_file
composer require 'drupal/editor_file:^1.4'

# Url to Video Filter
# This module allows users to paste a URL from various video sharing websites, and upon submission replaces the URL with the video from that URL. 
# https://www.drupal.org/project/url_to_video_filter
# composer require 'drupal/url_to_video_filter:^1.3'

# Twig Tweak
# Twig Tweak is a small module which provides a Twig extension with some useful functions and filters that can improve development experience.
# composer require 'drupal/twig_tweak:^2.4'

# Form Block
# composer require 'drupal/formblock:^1.0'

# Metatag Routes
# Allows to configure metatags for custom controllers generated by code.
# composer require 'drupal/metatag_routes:^1.0'

# reCAPTCHA
# composer require 'drupal/recaptcha:^2.4'

# Paragraphs
# https://www.drupal.org/project/paragraphs
# composer require 'drupal/paragraphs:^1.9'


